name = "Matthew Stanley"
email = "stanley.t.matthew@gmail.com"
description = "Aspiring professional nerd."
summary = "summary"
picture = "None"
phone = "+1 (802) 989-2201"
resume_pdf = "/assets/resume.pdf"
website = "https://mtstanley.dev"

[location]
address = "34 Cardinal Way"
postal_code = "VT 05753"
city = "Middlebury"
country_code = "US"
region = "Vermont"

[social]

  [social.twitter]
  username = "mstanleyth"
  url = "https://twitter.com/"

  [social.github]
  username = "mthstanley"
  url = "https://github.com/"

  [social.instagram]
  username = "3geeky5me"
  url = "https://instagram.com/"

  [social.linkedin]
  username = "matthew-stanley-90b5a8103"
  url = "https://linkedin.com/in/"

[[experiences]]
department = "Department of Computer Science"
position = "Research Assistant"
website = "http://www.middlebury.edu/academics/cs"
start_date = 2015-05-26
end_date = 2015-07-31
current = false
highlights = [
  "Designed and developed two graphical applications to compute and visualize  a selection of matching costs for stereo image pairs. These applications  also allow the user to manipulate the images including: omnidirectional  movement and horizontal/vertical image warping around an anchor point.\n",
  "Implemented both a native and web-based application in C++ and Javascript  respectively.\n",
  "Using the WebGL API and GLSL, parallelized the compute-intensive image  processing to take advantage of GPGPU allowing for interactive speeds  within a web browser environment.\n"
]
[experiences.company]
name = "Middlebury College"
location = "Middlebury, VT"

[[experiences]]
department = "Department of Computer Science"
position = "Teaching Assistant"
website = "http://www.middlebury.edu/academics/cs"
start_date = 2014-09-08
end_date = 2015-12-14
current = false
highlights = [
  "Computing for the Sciences Fall 2015: Graded Python  programming assignments for a class of 60 students, along with  providing one-on-one mentoring in a lab class of 30 students.\n",
  "Data Structures Spring 2015: Provided both numerical and written feedback on Java programming assignments for a class of  60 students.\n",
  "Computing for the Sciences Fall 2014: Graded a class  of 30 students on both style and correctness of programming  assignment solutions written in Python.\n"
]
[experiences.company]
name = "Middlebury College"
location = "Middlebury, VT"

[[experiences]]
department = "Department of Chemistry"
position = "Research Assistant"
website = "http://www.middlebury.edu/academics/chem"
start_date = 2012-06-01
end_date = 2012-08-31
current = false
highlights = [
  "Synthesized the protein methionine aminopeptidase (METAP 2) to be  utilized in researching the enzyme’s role in angiogenesis.\n",
  "Used UV-Vis spectroscopy to test for quality and quantity of protein  produced.\n",
  "Created and presented a poster for the Middlebury College research  symposium.\n"
]
[experiences.company]
name = "Middlebury College"
location = "Middlebury, VT"

[[experiences]]
department = "Back of the House"
position = "Kitchen Manager"
website = "http://americanflatbread.com/restaurants/middlebury-vt/"
start_date = 2010-06-01
current = true
highlights = [
  "Trained on all positions in the restaurant, both front and back of house. Proficient enough to smoothly manage 400 cover nights. Create and execute  catering menus for parties exceeding 100 individuals.\n",
  "Design and oversee the creation of new menu items and weekly specials  alongside the head chef.\n",
  "Manage the kitchen staff in the absence of the head chef.\n"
]
[experiences.company]
name = "American Flatbread"
location = "Middlebury, VT"

[[educations]]
institution = "Middlebury College"
website = "http://www.middlebury.edu"
major = "Computer Science"
minor = "Mathematics"
degree = "Bachelor of the Arts"
start_date = 2012-02-08
end_date = 2016-02-06
current = false
gpa = 3.91
achievements = [
  "summa cum laude",
  "phi beta kappa",
  "College Scholar 6 semesters"
]
course = ""
location = "Middlebury, VT"

[[skills]]
name = "Python"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "Java"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "C"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "Javascript"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "HTML"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "CSS"
level = "intermediate"
keywords = ""
category = "Programming Langauges"

[[skills]]
name = "Backbone.js"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "Node.js"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "WebGL"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "Flask"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "Django"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "jQuery"
level = "intermediate"
keywords = ""
category = "Libraries & Frameworks"

[[skills]]
name = "Unix"
level = "intermediate"
keywords = ""
category = "Operating Systems"

[[skills]]
name = "Mac OS X"
level = "intermediate"
keywords = ""
category = "Operating Systems"

[[skills]]
name = "Linux (Arch, Fedora)"
level = "intermediate"
keywords = ""
category = "Operating Systems"

[[skills]]
name = "git"
level = "intermediate"
keywords = ""
category = "Dev Tools"

[[skills]]
name = "gcc"
level = "intermediate"
keywords = ""
category = "Dev Tools"

[[skills]]
name = "make"
level = "intermediate"
keywords = ""
category = "Dev Tools"

[[projects]]
name = "Twender"
website = ""
source = "https://github.com/mthstanley/twender"
description = "Web application for determining the gender of a given Twitter user using the text of their tweets.\n"

[[projects]]
name = "Stockpot"
website = ""
source = "https://github.com/mthstanley/stockpot"
description = "Web application for storing and sharing your favorite recipes, with  an emphasis on encouraging social interaction between users.\n"
